### ISSUE TITLE
Compile Error on Angular 15.1.1

### ISSUE THREAD

**Issue by hobojoe** [rbalet/ngx-mat-input-tel#1] opened 2023-10-05 12:29 UTC
Hi  @rbalet ,

I've tested your updated version but the problem persisted:
```
Error: node_modules/ngx-mat-input-tel/lib/ngx-mat-input-tel.component.d.ts:91:97 - error TS2344: Type '{ preferredCountries: { alias: "preferredCountries"; required: false; }; enablePlaceholder: { alias: "enablePlaceholder"; required: false; }; inputPlaceholder: { alias: "inputPlaceholder"; required: false; }; ... 10 more ...; disabled: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"preferredCountries"' is incompatible with index signature.
    Type '{ alias: "preferredCountries"; required: false; }' is not assignable to type 'string'.
```

I believe is related to the Angular version I have: 15.1.1

That equivalent code from the ngx-mat-intl-tel-input  lib is different:
static ɵcmp: i0.ɵɵComponentDeclaration<NgxMatIntlTelInputComponent, "ngx-mat-intl-tel-input", never, { "preferredCountries": "preferredCountries"; "enablePlaceholder": "enablePlaceholder"; "inputPlaceholder": "inputPlaceholder"; "cssClass": "cssClass"; "name": "name"; "onlyCountries": "onlyCountries"; "errorStateMatcher": "errorStateMatcher"; "enableSearch": "enableSearch"; "searchPlaceholder": "searchPlaceholder"; "describedBy": "describedBy"; "format": "format"; "placeholder": "placeholder"; "required": "required"; "disabled": "disabled"; }, { "countryChanged": "countryChanged"; }, never, never, true>;

Don't know if there is something else that can be done to make it work with my version of angular.

Thanks!

**Comment by rbalet** [comment] 2023-10-05 12:37
@hobojoe I cannot reproduce your error.

Would it be possible for you to provide a stackblitz example of it ?

**Comment by rbalet** [comment] 2023-10-26 07:49
@hobojoe I'm closing this issue as not reproducible

**Closed by rbalet** 2023-10-26 07:49 UTC
